server:
  port : 9090
security:
  oauth2:
    resourceserver:
      jwk:
        #jwk-set-uri: http://localhost:8080/o/oauth2/jwks
        jwk-set-uri: https://webserver-lctXYZ-prd.lfr.cloud/o/oauth2/jwks
management:
  endpoints:
    jmx:
      exposure:
        include: "health"
liferay:
  headless:
    api:
      base:
        #url: http://localhost:8080/o
        url: https://webserver-lctXYZ-prd.lfr.cloud/o
    my-user-account: /my-user-account
logging:
  level:
    root: INFO
    com.liferay.demo.cmschat: DEBUG
    org.springframework.web: DEBUG

openai:
  key: